Increase the priority of the libopenmpi-dev package to make sure OpenMPI is used before mpich. Otherwise, it causes issues like: «PKGBUILDDIR»/./src/mpi.c:143: undefined reference to `ompi_mpi_comm_world' «PKGBUILDDIR»/./src/mpi.c:143: undefined reference to `ompi_mpi_double'
git-svn-id: svn://svn.debian.org/svn/pkg-openmpi/openmpi/trunk@337 73dcd3bc-d895-4a24-a01c-79f548e222e3